# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: replication.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'replication.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11replication.proto\x12\x0breplication\"-\n\rAppendRequest\x12\r\n\x05\x63have\x18\x01 \x01(\t\x12\r\n\x05valor\x18\x02 \x01(\t\"3\n\x0e\x41ppendResponse\x12\x0f\n\x07sucesso\x18\x01 \x01(\x08\x12\x10\n\x08mensagem\x18\x02 \x01(\t\"\x1d\n\x0cQueryRequest\x12\r\n\x05\x63have\x18\x01 \x01(\t\"1\n\rQueryResponse\x12\r\n\x05valor\x18\x01 \x01(\t\x12\x11\n\tcommitted\x18\x02 \x01(\x08\"$\n\x0bSyncRequest\x12\x15\n\rultimo_offset\x18\x01 \x01(\x05\"7\n\x0cSyncResponse\x12\'\n\x08\x65ntradas\x18\x01 \x03(\x0b\x32\x15.replication.LogEntry\"G\n\x08LogEntry\x12\r\n\x05\x65poca\x18\x01 \x01(\x05\x12\x0e\n\x06offset\x18\x02 \x01(\x05\x12\r\n\x05\x63have\x18\x03 \x01(\t\x12\r\n\x05valor\x18\x04 \x01(\t\".\n\rCommitRequest\x12\r\n\x05\x65poca\x18\x01 \x01(\x05\x12\x0e\n\x06offset\x18\x02 \x01(\x05\"0\n\x0b\x41\x63kResponse\x12\x0f\n\x07sucesso\x18\x01 \x01(\x08\x12\x10\n\x08mensagem\x18\x02 \x01(\t2\xd9\x01\n\x0cLiderServico\x12\x45\n\nAppendData\x12\x1a.replication.AppendRequest\x1a\x1b.replication.AppendResponse\x12\x42\n\tQueryData\x12\x19.replication.QueryRequest\x1a\x1a.replication.QueryResponse\x12>\n\x07SyncLog\x12\x18.replication.SyncRequest\x1a\x19.replication.SyncResponse2\x93\x01\n\x0eReplicaServico\x12<\n\tPushEntry\x12\x15.replication.LogEntry\x1a\x18.replication.AckResponse\x12\x43\n\x0b\x43ommitEntry\x12\x1a.replication.CommitRequest\x1a\x18.replication.AckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'replication_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_APPENDREQUEST']._serialized_start=34
  _globals['_APPENDREQUEST']._serialized_end=79
  _globals['_APPENDRESPONSE']._serialized_start=81
  _globals['_APPENDRESPONSE']._serialized_end=132
  _globals['_QUERYREQUEST']._serialized_start=134
  _globals['_QUERYREQUEST']._serialized_end=163
  _globals['_QUERYRESPONSE']._serialized_start=165
  _globals['_QUERYRESPONSE']._serialized_end=214
  _globals['_SYNCREQUEST']._serialized_start=216
  _globals['_SYNCREQUEST']._serialized_end=252
  _globals['_SYNCRESPONSE']._serialized_start=254
  _globals['_SYNCRESPONSE']._serialized_end=309
  _globals['_LOGENTRY']._serialized_start=311
  _globals['_LOGENTRY']._serialized_end=382
  _globals['_COMMITREQUEST']._serialized_start=384
  _globals['_COMMITREQUEST']._serialized_end=430
  _globals['_ACKRESPONSE']._serialized_start=432
  _globals['_ACKRESPONSE']._serialized_end=480
  _globals['_LIDERSERVICO']._serialized_start=483
  _globals['_LIDERSERVICO']._serialized_end=700
  _globals['_REPLICASERVICO']._serialized_start=703
  _globals['_REPLICASERVICO']._serialized_end=850
# @@protoc_insertion_point(module_scope)
